# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linyufly/CUDATracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linyufly/CUDATracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linyufly/CUDATracer/CMakeFiles /home/linyufly/CUDATracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linyufly/CUDATracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fastvection

# Build rule for target.
fastvection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fastvection
.PHONY : fastvection

# fast build rule for target.
fastvection/fast:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/build
.PHONY : fastvection/fast

lcs.o: lcs.cpp.o
.PHONY : lcs.o

# target to build an object file
lcs.cpp.o:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcs.cpp.o
.PHONY : lcs.cpp.o

lcs.i: lcs.cpp.i
.PHONY : lcs.i

# target to preprocess a source file
lcs.cpp.i:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcs.cpp.i
.PHONY : lcs.cpp.i

lcs.s: lcs.cpp.s
.PHONY : lcs.s

# target to generate assembly for a file
lcs.cpp.s:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcs.cpp.s
.PHONY : lcs.cpp.s

lcsGeometry.o: lcsGeometry.cpp.o
.PHONY : lcsGeometry.o

# target to build an object file
lcsGeometry.cpp.o:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsGeometry.cpp.o
.PHONY : lcsGeometry.cpp.o

lcsGeometry.i: lcsGeometry.cpp.i
.PHONY : lcsGeometry.i

# target to preprocess a source file
lcsGeometry.cpp.i:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsGeometry.cpp.i
.PHONY : lcsGeometry.cpp.i

lcsGeometry.s: lcsGeometry.cpp.s
.PHONY : lcsGeometry.s

# target to generate assembly for a file
lcsGeometry.cpp.s:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsGeometry.cpp.s
.PHONY : lcsGeometry.cpp.s

lcsUnitTest.o: lcsUnitTest.cpp.o
.PHONY : lcsUnitTest.o

# target to build an object file
lcsUnitTest.cpp.o:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsUnitTest.cpp.o
.PHONY : lcsUnitTest.cpp.o

lcsUnitTest.i: lcsUnitTest.cpp.i
.PHONY : lcsUnitTest.i

# target to preprocess a source file
lcsUnitTest.cpp.i:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsUnitTest.cpp.i
.PHONY : lcsUnitTest.cpp.i

lcsUnitTest.s: lcsUnitTest.cpp.s
.PHONY : lcsUnitTest.s

# target to generate assembly for a file
lcsUnitTest.cpp.s:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsUnitTest.cpp.s
.PHONY : lcsUnitTest.cpp.s

lcsUtility.o: lcsUtility.cpp.o
.PHONY : lcsUtility.o

# target to build an object file
lcsUtility.cpp.o:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsUtility.cpp.o
.PHONY : lcsUtility.cpp.o

lcsUtility.i: lcsUtility.cpp.i
.PHONY : lcsUtility.i

# target to preprocess a source file
lcsUtility.cpp.i:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsUtility.cpp.i
.PHONY : lcsUtility.cpp.i

lcsUtility.s: lcsUtility.cpp.s
.PHONY : lcsUtility.s

# target to generate assembly for a file
lcsUtility.cpp.s:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/lcsUtility.cpp.s
.PHONY : lcsUtility.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fastvection.dir/build.make CMakeFiles/fastvection.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fastvection"
	@echo "... rebuild_cache"
	@echo "... lcs.o"
	@echo "... lcs.i"
	@echo "... lcs.s"
	@echo "... lcsGeometry.o"
	@echo "... lcsGeometry.i"
	@echo "... lcsGeometry.s"
	@echo "... lcsUnitTest.o"
	@echo "... lcsUnitTest.i"
	@echo "... lcsUnitTest.s"
	@echo "... lcsUtility.o"
	@echo "... lcsUtility.i"
	@echo "... lcsUtility.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

